name: Build and Push Docker Image

on:
  push:
    paths-ignore:
      - 'gifted-children-helper-frontend/**'
    branches:
      - main
      - master
      - feat-*
      - feature-*

env:
  DOCKER_USERNAME: jaimevalero78
  DOCKER_REPOSITORY: guiding-families-backend

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${GITHUB_SHA::7}
          cache-from: type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:buildcache,mode=max

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: gifted-children-helper

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gifted-children-helper \
            --image=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${GITHUB_SHA::7} \
            --region=europe-southwest1 \
            --platform=managed \
            --project=gifted-children-helper